;=======================================
; AMI Configuration para AloiaTelecom
;=======================================

[aloia_admin]
secret = AlOiA_AMI_2025_Secure
deny = 0.0.0.0/0.0.0.0
permit = 0.0.0.0/0.0.0.0
read = system,call,log,verbose,command,agent,user,config,dtmf,reporting,cdr,dialplan,originate
write = system,call,log,verbose,command,agent,user,config,dtmf,reporting,cdr,dialplan,originate
writetimeout = 5000

[aloia_app]
secret = AlOiA_APP_2025_Secure
deny = 0.0.0.0/0.0.0.0
permit = 0.0.0.0/0.0.0.0
read = system,call,agent,user,originate
write = system,call,agent,user,originate
writetimeout = 5000
